language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-thundr-module' ]; then cd .. && eval "mv $currentfolder generator-thundr-module" && cd generator-thundr-module; fi

